tracking:
    path: /track/{carrier}
    controller: Shwrm\Tracking\Controller\TrackingController::trackAction
    requirements:
        carrier: '\w+'

status:
    path: /status
    controller: Shwrm\Tracking\Controller\HealthCheckController::heartbeatAction
